### ISSUE TITLE
Create Zapier when WPCS releases, create issue here

### ISSUE THREAD

**Issue by aubreypwd** [WebDevStudios/php-coding-standards#15]
When a new tag is added, we can use Zapier and this feed `https://make.wordpress.org/core/tag/wpcs/feed/` ([WPCS Releases](https://github.com/WordPress/WordPress-Coding-Standards/releases)) to create a new issue in this repo so we know we need to update with WPCS.

I would like it to prefix the Issue Title with "WordPress Coding Standards" so that the title ends up being "WordPress Coding Standards (Tag)", e.g. "WordPress Coding Standards 2.1.1". It should link back to the tag release notes if we can.

**Comment by aubreypwd** [comment]
@gregrickaby I tried to do this, but my Zapier can't get into WebDevStudios Github, so I know we have an account, can you either create this or give me access so I can?

**Comment by aubreypwd** [comment]
Could we also have it add the label `WPCS`?

**Comment by gregrickaby** [comment]
@aubreypwd Because neither of us are members of the WordPress organization, Zapier is unable to auth. I even tried passing several custom URLs (and the REST API URL) without avail.

![screenshot](https://dl.dropbox.com/s/18h3345zts3caoa/Screenshot%202019-10-07%2009.07.58.png?dl=0)

**Comment by aubreypwd** [comment]
Did you try feeding this RSS feed https://make.wordpress.org/core/tag/wpcs/feed/ instead of Github releases? That feed could trigger an issue to get created too?

**Comment by gregrickaby** [comment]
@aubreypwd This is done. See #18 (which was a test)

**Comment by aubreypwd** [comment]
Confirmed this is working, thanks! 🌮
