### ISSUE TITLE
 WordPress.org #wpcs - PHP Coding Standards Changes

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/php-coding-standards#20]
https://make.wordpress.org/core/2019/07/12/php-coding-standards-changes/
This is a follow-up to several changes proposed a few months ago. While reading these changes, it’s important to keep in mind that they only apply to WordPress Core: you can (and should) choose practices that best suits your development style for your own plugins and themes. The coding standards are intentionally opinionated, and will […]

**Comment by aubreypwd** [comment]
Dup of https://github.com/WebDevStudios/php-coding-standards/issues/9
