### ISSUE TITLE
Setting up local project required adding respository

### ISSUE THREAD

**Issue by salcode** [WebDevStudios/php-coding-standards#8]
When I was setting up a local copy to work on, I had to deviate a little from the `README.md`.

Specifically, I had to include a repositories section in `composer.json` using the following command

```
composer config repositories.wds-php-coding-standards vcs https://github.com/WebDevStudios/php-coding-standards.git
```

**Comment by aubreypwd** [comment]
Actually, as of now, you shouldn't have to do this because this is now [on packagist.org](https://packagist.org/packages/webdevstudios/php-coding-standards).

**Comment by salcode** [comment]
Hmm... I'll try again without it - thanks.

**Comment by salcode** [comment]
Yep, worked great. Thank you 👍
